/*
 * jpEnvironment.java
 *
 * Created on August 23, 2008, 12:48 PM
 */

package de.kechel.particlemovementsimulator.gui;

import java.util.*;

/**
 *
 * @author  jan
 */
public class jpEnvironment extends javax.swing.JPanel {
    
    /** Creates new form jpEnvironment */
    public jpEnvironment() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfFormulaEx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfFormulaEy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfFormulaEz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfFormulaBx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfFormulaBy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfFormulaBz = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfFormulaGx = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfFormulaGy = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfFormulaGz = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 120));
        jLabel1.setText("Magnetical field");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Formulas to calculate electrical field strength for a specified position (x,y,z) at a specified time (t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Ex = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel3, gridBagConstraints);

        jtfFormulaEx.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaEx, gridBagConstraints);

        jLabel4.setText("Ey = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel4, gridBagConstraints);

        jtfFormulaEy.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaEy, gridBagConstraints);

        jLabel5.setText("Ez = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel5, gridBagConstraints);

        jtfFormulaEz.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaEz, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 0, 120));
        jLabel6.setText("Electrical field");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel6, gridBagConstraints);

        jLabel7.setText("Formulas to calculate magnetic field strength for a specified position (x,y,z) at a specified time (t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("Bx = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel8, gridBagConstraints);

        jtfFormulaBx.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaBx, gridBagConstraints);

        jLabel9.setText("By = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel9, gridBagConstraints);

        jtfFormulaBy.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaBy, gridBagConstraints);

        jLabel10.setText("Bz = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel10, gridBagConstraints);

        jtfFormulaBz.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaBz, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel11.setForeground(new java.awt.Color(0, 0, 120));
        jLabel11.setText("Gravitational field");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel11, gridBagConstraints);

        jLabel12.setText("Formulas to calculate gravitational field strength for a specified position (x,y,z) at a specified time (t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel12, gridBagConstraints);

        jLabel13.setText("Gx = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel13, gridBagConstraints);

        jtfFormulaGx.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaGx, gridBagConstraints);

        jLabel14.setText("Gy = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel14, gridBagConstraints);

        jtfFormulaGy.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaGy, gridBagConstraints);

        jLabel15.setText("Gz = f(x,y,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel15, gridBagConstraints);

        jtfFormulaGz.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaGz, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizePropertiesFromGui(Properties p)
    {
        p.setProperty("eFormulaBx", jtfFormulaBx.getText());
        p.setProperty("eFormulaBy", jtfFormulaBy.getText());
        p.setProperty("eFormulaBz", jtfFormulaBz.getText());
        p.setProperty("eFormulaEx", jtfFormulaEx.getText());
        p.setProperty("eFormulaEy", jtfFormulaEy.getText());
        p.setProperty("eFormulaEz", jtfFormulaEz.getText());
        p.setProperty("eFormulaGx", jtfFormulaGx.getText());
        p.setProperty("eFormulaGy", jtfFormulaGy.getText());
        p.setProperty("eFormulaGz", jtfFormulaGz.getText());
    }
    
    public void actualizeGuiFromProperties(Properties p)
    {
        
        jtfFormulaBx.setText(p.getProperty("eFormulaBx"));
        jtfFormulaBy.setText(p.getProperty("eFormulaBy"));
        jtfFormulaBz.setText(p.getProperty("eFormulaBz"));
        jtfFormulaEx.setText(p.getProperty("eFormulaEx"));
        jtfFormulaEy.setText(p.getProperty("eFormulaEy"));
        jtfFormulaEz.setText(p.getProperty("eFormulaEz"));
        jtfFormulaGx.setText(p.getProperty("eFormulaGx"));
        jtfFormulaGy.setText(p.getProperty("eFormulaGy"));
        jtfFormulaGz.setText(p.getProperty("eFormulaGz"));
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfFormulaBx;
    private javax.swing.JTextField jtfFormulaBy;
    private javax.swing.JTextField jtfFormulaBz;
    private javax.swing.JTextField jtfFormulaEx;
    private javax.swing.JTextField jtfFormulaEy;
    private javax.swing.JTextField jtfFormulaEz;
    private javax.swing.JTextField jtfFormulaGx;
    private javax.swing.JTextField jtfFormulaGy;
    private javax.swing.JTextField jtfFormulaGz;
    // End of variables declaration//GEN-END:variables
    
}
