/*
 * jpForces.java
 *
 * Created on August 23, 2008, 1:24 PM
 */

package de.kechel.particlemovementsimulator.gui;

import java.util.*;

/**
 *
 * @author  jan
 */
public class jpInteractingForces extends javax.swing.JPanel {
    
    /** Creates new form jpForces */
    public jpInteractingForces() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfFormulaFex = new javax.swing.JTextField();
        jtfFormulaFey = new javax.swing.JTextField();
        jtfFormulaFez = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 120));
        jLabel1.setText("Force on particle p0 because of particle pn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Fiz = f(x,y,z,q,a,b,c,s,d,e,f,m,u,v,w,p,g,h,i,t,j,k,l,n)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Known variables:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Fiy = f(x,y,z,q,a,b,c,s,d,e,f,m,u,v,w,p,g,h,i,t,j,k,l,n)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Fix = f(x,y,z,q,a,b,c,s,d,e,f,m,u,v,w,p,g,h,i,t,j,k,l,n)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel5, gridBagConstraints);

        jLabel8.setText("p0: Position: x, y, z, electric charge: q, velocity as (a,b,c) or speed(s) and direction (d,e,f), mass: m");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel8, gridBagConstraints);

        jLabel9.setText("pn: Position: u, v, w, electric charge: p, velocity as (g,h,i) or speed(t) and direction (j,k,l), mass: n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel9, gridBagConstraints);

        jtfFormulaFex.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaFex, gridBagConstraints);

        jtfFormulaFey.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaFey, gridBagConstraints);

        jtfFormulaFez.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaFez, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizePropertiesFromGui(Properties p)
    {
        p.setProperty("interactingforceFormulaFex", jtfFormulaFex.getText());
        p.setProperty("interactingforceFormulaFey", jtfFormulaFey.getText());
        p.setProperty("interactingforceFormulaFez", jtfFormulaFez.getText());
    }
    
    public void actualizeGuiFromProperties(Properties p)
    {
        jtfFormulaFex.setText(p.getProperty("interactingforceFormulaFex"));
        jtfFormulaFey.setText(p.getProperty("interactingforceFormulaFey"));
        jtfFormulaFez.setText(p.getProperty("interactingforceFormulaFez"));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfFormulaFex;
    private javax.swing.JTextField jtfFormulaFey;
    private javax.swing.JTextField jtfFormulaFez;
    // End of variables declaration//GEN-END:variables
    
}
