/*
 * jpTime.java
 *
 * Created on August 23, 2008, 2:04 PM
 */

package de.kechel.particlemovementsimulator.gui;

import java.util.*;

/**
 *
 * @author  jan
 */
public class jpTime extends javax.swing.JPanel {
    
    /** Creates new form jpTime */
    public jpTime() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfStartTime = new javax.swing.JTextField();
        jtfEndTime = new javax.swing.JTextField();
        jtfStepSize = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfFormulaVx = new javax.swing.JTextField();
        jtfFormulaVy = new javax.swing.JTextField();
        jtfFormulaVz = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfFormulaPy = new javax.swing.JTextField();
        jtfFormulaPx = new javax.swing.JTextField();
        jtfFormulaPz = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jlTotalSteps = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 120));
        jLabel1.setText("Timeframe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Start time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("End time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Step size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 0, 120));
        jLabel5.setText("Calculate particles next velocity");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("Variables:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel6, gridBagConstraints);

        jtfStartTime.setColumns(10);
        jtfStartTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfStartTimeKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfStartTime, gridBagConstraints);

        jtfEndTime.setColumns(10);
        jtfEndTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEndTimeKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfEndTime, gridBagConstraints);

        jtfStepSize.setColumns(10);
        jtfStepSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfStepSizeKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfStepSize, gridBagConstraints);

        jLabel7.setText("Particles mass (m)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("Overall force on particle (a,b,c)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel8, gridBagConstraints);

        jLabel9.setText("Particles current velocity (d,e,f) or speed (s) and direction (g,h,i)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel9, gridBagConstraints);

        jLabel11.setText("Vx(n+1) = f(a,b,c,d,e,f,g,h,i,s,m,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel11, gridBagConstraints);

        jLabel12.setText("Vy(n+1) = f(a,b,c,d,e,f,g,h,i,s,m,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel12, gridBagConstraints);

        jLabel13.setText("Vz(n+1) = f(a,b,c,d,e,f,g,h,i,s,m,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel13, gridBagConstraints);

        jtfFormulaVx.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaVx, gridBagConstraints);

        jtfFormulaVy.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaVy, gridBagConstraints);

        jtfFormulaVz.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaVz, gridBagConstraints);

        jLabel14.setText("Particles mass (m)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel14, gridBagConstraints);

        jLabel15.setText("Particles old velocity (a,b,c) or speed (d) and direction (e,f,g)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel15, gridBagConstraints);

        jLabel16.setText("Particles new velocity (h,i,j) or speed (k) and direction (l,n,o)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel16, gridBagConstraints);

        jLabel17.setText("Particles current position (x,y,z)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel17, gridBagConstraints);

        jLabel18.setText("Px(n+1) = f(a,d,e,h,k,l,m,x,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel18, gridBagConstraints);

        jLabel19.setText("Py(n+1) = f(b,d,f,i,k,n,m,y,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel19, gridBagConstraints);

        jLabel20.setText("Pz(n+1) = f(c,d,g,j,k,o,m,z,t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel20, gridBagConstraints);

        jtfFormulaPy.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaPy, gridBagConstraints);

        jtfFormulaPx.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaPx, gridBagConstraints);

        jtfFormulaPz.setColumns(50);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jtfFormulaPz, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
        jLabel21.setForeground(new java.awt.Color(0, 0, 120));
        jLabel21.setText("Calculate particles next position");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        add(jLabel21, gridBagConstraints);

        jLabel22.setText("Variables:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel22, gridBagConstraints);

        jLabel10.setText("Time intervall length (t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel10, gridBagConstraints);

        jLabel23.setText("Time intervall length (t)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel23, gridBagConstraints);

        jLabel24.setText("Total number of Steps");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jLabel24, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jlTotalSteps, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTotalStepsLabel()
    {
        if( this.jtfStartTime.getText().length() > 0 && this.jtfEndTime.getText().length() > 0 && this.jtfStepSize.getText().length() > 0)
        {
            double start = Double.parseDouble(jtfStartTime.getText());
            double end = Double.parseDouble(jtfEndTime.getText());
            double step = Double.parseDouble(jtfStepSize.getText());
            this.jlTotalSteps.setText(String.valueOf((end-start)/step));
        }
        else
        {
            this.jlTotalSteps.setText("-");
        }
    }
    private void jtfStartTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStartTimeKeyReleased
        updateTotalStepsLabel();
    }//GEN-LAST:event_jtfStartTimeKeyReleased

    private void jtfEndTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEndTimeKeyReleased
        updateTotalStepsLabel();
    }//GEN-LAST:event_jtfEndTimeKeyReleased

    private void jtfStepSizeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfStepSizeKeyReleased
        updateTotalStepsLabel();
    }//GEN-LAST:event_jtfStepSizeKeyReleased
    
    public void actualizePropertiesFromGui(Properties p)
    {
        p.setProperty("tEndTime", jtfEndTime.getText());
        p.setProperty("tStartTime", jtfStartTime.getText());
        p.setProperty("tStepSize", jtfStepSize.getText());
        p.setProperty("tFormulaPx", jtfFormulaPx.getText());
        p.setProperty("tFormulaPy", jtfFormulaPy.getText());
        p.setProperty("tFormulaPz", jtfFormulaPz.getText());
        p.setProperty("tFormulaVx", jtfFormulaVx.getText());
        p.setProperty("tFormulaVy", jtfFormulaVy.getText());
        p.setProperty("tFormulaVz", jtfFormulaVz.getText());
    }
    public void actualizeGuiFromProperties(Properties p)
    {
        jtfEndTime.setText(p.getProperty("tEndTime"));
        jtfStartTime.setText(p.getProperty("tStartTime"));
        jtfStepSize.setText(p.getProperty("tStepSize"));
        jtfFormulaPx.setText(p.getProperty("tFormulaPx"));
        jtfFormulaPy.setText(p.getProperty("tFormulaPy"));
        jtfFormulaPz.setText(p.getProperty("tFormulaPz"));
        jtfFormulaVx.setText(p.getProperty("tFormulaVx"));
        jtfFormulaVy.setText(p.getProperty("tFormulaVy"));
        jtfFormulaVz.setText(p.getProperty("tFormulaVz"));
        updateTotalStepsLabel();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlTotalSteps;
    private javax.swing.JTextField jtfEndTime;
    private javax.swing.JTextField jtfFormulaPx;
    private javax.swing.JTextField jtfFormulaPy;
    private javax.swing.JTextField jtfFormulaPz;
    private javax.swing.JTextField jtfFormulaVx;
    private javax.swing.JTextField jtfFormulaVy;
    private javax.swing.JTextField jtfFormulaVz;
    private javax.swing.JTextField jtfStartTime;
    private javax.swing.JTextField jtfStepSize;
    // End of variables declaration//GEN-END:variables
    
}
